[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "data_gen"
authors = [{name = "Seraphin Auffinger", email = "seraphin@auffinger.net"}]
dynamic = ["version", "description"]
